const indumentaria = [
  {
    imagen: "./img/remeras/buzo dior grafiti.jpg",
    id: 1,
    nombre: "Buzo Dior <br> Grafiti",
    precio: "33.700",
  },
  {
    imagen: "./img/remeras/buzo kenzo paris.jpg",
    id: 2,
    nombre: "Buzo Kenzo <br> Paris",
    precio: "45.000",
  },
  {
    imagen: "./img/remeras/buzo essentials.webp",
    id: 3,
    nombre: "Buzo <br> Essentials",
    precio: "70.000",
  },
  {
    imagen: "./img/remeras/buzo burberry blanco.jpg",
    id: 4,
    nombre: "Burberry <br> White",
    precio: "40.000",
  },
  {
    imagen: "../img/remeras/buzo christian dior blanco.jpg",
    id: 5,
    nombre: "Buzo Christian Dior <br> White",
    precio: "45.000",
  },
  {
    imagen: "../img/remeras/Guccixbalenciaga.webp",
    id: 6,
    nombre: "Gucci x <br>Balenciaga",
    precio: "34.000",
  },
  {
    imagen: "../img/remeras/buzo off-white.webp",
    id: 7,
    nombre: "Buzo <br> Off-White",
    precio: "22.800",
  },
  {
    imagen: "../img/remeras/buzo givenchy.jpg",
    id: 8,
    nombre: "Buzo <br> Givenchy",
    precio: "18.000",
  },
  {
    imagen: "../img/remeras/campera lakers kobe.jpg",
    id: 9,
    nombre: "Buzo Lakers <br> Kobe",
    precio: "70.800",
  },
  {
    imagen: "../img/remeras/buzo essentials4.webp",
    id: 10,
    nombre: "Essentials Black",
    precio: "38.600",
  },
  {
    imagen: "../img/remeras/buzo christian dior negro.jpg",
    id: 11,
    nombre: "Christian Dior Black",
    precio: "45.000",
  },
  {
    imagen: "../img/remeras/Buzo louis vuitton.webp",
    id: 12,
    nombre: "Louis Vuitton",
    precio: "45.000",
  },
  {
    imagen: "./img/remeras/campera supreme gris.jpg",
    id: 13,
    nombre: "Campera <br> Supreme",
    precio: "18.000",
  },
  {
    imagen: "./img/remeras/Camperas JORDAN white.webp",
    id: 14,
    nombre: "Campera <br> Jordan  White",
    precio: "29.200",
  },
  {
    imagen: "./img/remeras/campera north rosa.jpg",
    id: 15,
    nombre: "Campera  <br> Nort Face",
    precio: "40.000",
  },
  {
    imagen: "../img/remeras/campera negra north.jpg",
    id: 16,
    nombre: "Campera The Nort <br> Face",
    precio: "40.000",
  },
  {
    imagen: "../img/remeras/Camperas JORDAN black white.webp",
    id: 17,
    nombre: "The Nort <br> Face",
    precio: "40.000",
  },
  {
    imagen: "../img/remeras/Louis Vuitton Varsity Jacket 'green'.jpeg",
    id: 18,
    nombre: "Louis Vuitton <br> Varsity Jacket",
    precio: "68.000",
  },
];
